src/components/Layout/components/ContentLayout/contentLayout.styles.ts
=> fix: update content layout content styles (#44)

src/apis/azul/common/entities.ts, src/components/Export/components/ExportToTerra/exportToTerra.tsx, src/hooks/useEntityList.ts, src/hooks/useURLFilterParams.ts, src/hooks/useUpdateURLSearchParams.ts, src/providers/exploreState.tsx, src/providers/exploreState/constants.ts, src/providers/exploreState/utils.ts
=> feat: add feature flags to view builder context (#43)

src/components/Export/common/utils.ts
=> feat: fix export to terra response URL format (#52)

src/components/common/AnchorLink/anchorLink.styles.ts
=> feat: fix anchor link position style (#65)

src/hooks/useSessionTimeout.ts
=> feat: clear inactivitytimeout param when user closes inactivity timeout banner (#42)

src/components/Filter/components/FilterLabel/filterLabel.styles.ts, src/components/Filter/components/Filters/filters.styles.ts, src/components/Filter/components/Filters/filters.tsx
=> feat: display named filter groups (#69)

src/components/common/Alert/components/AlertText/alertText.styles.ts
=> feat: add alert text styled component (#79)

src/components/Detail/components/DetailViewTable/detailViewTable.tsx, src/components/Index/index.tsx, src/components/Table/components/TableToolbar/tableToolbar.styles.ts, src/components/Table/components/TableToolbar/tableToolbar.tsx, src/views/ExploreView/exploreView.tsx, types/data-explorer-ui.d.ts
=> feat: exploreview component props should include classname (#81)

src/components/Table/common/utils.ts, src/components/Table/components/TableHead/components/HeadSelectionCell/headSelectionCell.tsx, src/components/Table/table.tsx, src/components/TableCreator/tableCreator.tsx, src/providers/exploreState.tsx, src/providers/exploreState/utils.ts, src/views/ExploreView/exploreView.tsx
=> feat: row selection should clear when entity list is filtered (#84)

src/components/Table/components/TableToolbar/components/RowSelection/components/DropdownMenu/dropdownMenu.tsx, src/components/common/DropdownMenu/common/entities.ts, src/components/common/DropdownMenu/dropdownMenu.tsx, src/components/common/IconButton/iconButton.styles.ts, src/components/common/IconButton/iconButton.tsx
=> feat: dropdownmenu component button prop updated to render an icon button (#83)

src/config/entities.ts, src/hooks/useCategoryFilter.ts
=> feat: allow category filters to format category values (#89)

src/components/Links/common/constants.ts, src/components/Links/common/entities.ts, src/components/Links/common/utils.ts, src/components/Links/components/Link/components/ExploreViewLink/exploreViewLink.tsx, src/components/Links/components/Link/link.tsx, src/providers/exploreState.tsx, src/providers/exploreState/initializer/constants.ts, src/providers/exploreState/initializer/utils.ts, src/providers/exploreState/payloads/entities.ts, src/providers/exploreState/utils.ts, src/theme/common/components.ts
=> feat: add action to explore state to update filter state from link parameters (#93)

src/components/common/Progress/components/CircularProgress/circularProgress.styles.ts, src/components/common/Progress/components/CircularProgress/circularProgress.tsx, src/components/common/Progress/components/CircularProgress/components/CircularProgressTrack/circularProgressTrack.styles.ts, src/components/common/Progress/components/CircularProgress/components/CircularProgressTrack/circularProgressTrack.tsx, src/styles/common/mixins/colors.ts, src/theme/common/components.ts, src/theme/theme.ts, types/data-explorer-ui.d.ts
=> feat: create circular progress indicator (#95)

src/theme/common/components.ts
=> fix: alert progress indicator theme style (#95)

src/components/Table/table.tsx, src/config/entities.ts, src/providers/exploreState/initializer/utils.ts
=> feat: saved filters should be configured to allow sorting (#104)

src/components/Links/components/Link/components/ExploreViewLink/exploreViewLink.tsx, src/components/Table/table.tsx, src/providers/exploreState.tsx, src/providers/exploreState/payloads/entities.ts
=> feat: link component with filter parameters should also be configured with sorting (#106)

package-lock.json, package.json, tsconfig.json
=> chore: update tsconfig.json (#115)

src/common/entities.ts, src/components/Index/components/Tabs/common/utils.ts, src/components/Index/components/Tabs/tabs.tsx, src/components/Layout/components/Header/common/constants.ts, src/components/Layout/components/Header/common/entities.ts, src/components/Layout/components/Header/common/utils.ts, src/components/Layout/components/Header/components/Announcements/announcements.tsx, src/components/Layout/components/Header/components/Content/components/Actions/actions.tsx, src/components/Layout/components/Header/components/Content/components/Actions/components/Authentication/components/RequestAuthentication/requestAuthentication.tsx, src/components/Layout/components/Header/components/Content/components/Actions/components/Menu/components/Toolbar/toolbar.tsx, src/components/Layout/components/Header/components/Content/components/Actions/components/Menu/menu.tsx, src/components/Layout/components/Header/components/Content/components/Actions/components/Search/components/SearchButton/searchButton.tsx, src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationMenu/navigationMenu.tsx, src/components/Layout/components/Header/components/Content/components/Navigation/navigation.styles.ts, src/components/Layout/components/Header/components/Content/components/Navigation/navigation.tsx, src/components/Layout/components/Header/header.stories.tsx, src/components/Layout/components/Header/header.styles.ts, src/components/Layout/components/Header/header.tsx, src/components/Layout/components/Header/hooks/useHeaderVisibility.ts, src/components/Layout/components/Header/hooks/useMeasureHeader.ts, src/config/entities.ts, src/config/utils.ts, src/hooks/useBreakpoint.ts, src/hooks/useBreakpointHelper.ts, src/hooks/useCurrentBreakpoint.ts, src/hooks/useMenu.ts, src/views/ExploreView/exploreView.tsx
=> feat: make index tabs optional (#121)

src/components/Layout/components/Header/header.tsx
=> fix: fix pathname is null on header component (#129)

src/components/Layout/components/Header/common/entities.ts, src/components/Layout/components/Header/components/Content/components/Actions/components/Menu/components/Toolbar/toolbar.tsx, src/components/Layout/components/Header/components/Content/components/Logo/logo.styles.ts, src/components/Layout/components/Header/components/Content/components/Logo/logo.tsx, src/components/Layout/components/Header/components/Content/components/Navigation/common/utils.ts, src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationMenuItems/navigationMenuItems.tsx, src/components/Layout/components/Header/components/Content/components/Navigation/navigation.tsx, src/components/Layout/components/Header/components/Content/components/Slogan/slogan.styles.ts, src/components/Layout/components/Header/header.styles.ts, src/components/Layout/components/Nav/nav.styles.ts
=> feat: update header navigation to match link path by startswith or equal (#134)

src/components/Export/components/ExportToTerra/components/ExportToTerraReady/exportToTerraReady.tsx, src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/FormStep/components/AcceptTerraTOS/acceptTerraTOS.tsx, src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/FormStep/components/ConnectTerraToNIHAccount/connectTerraToNIHAccount.tsx, src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/FormStep/components/CreateTerraAccount/createTerraAccount.tsx, src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationButtonLabel/navigationButtonLabel.tsx, src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationDrawer/navigationDrawer.styles.ts, src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationDrawer/navigationDrawer.tsx, src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationMenu/common/constants.ts, src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationMenu/navigationMenu.styles.ts, src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationMenu/navigationMenu.tsx, src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationMenuItems/navigationMenuItems.tsx, src/components/Layout/components/Header/components/Content/components/Navigation/navigation.tsx, src/components/Layout/components/Header/header.styles.ts, src/components/Links/common/entities.ts, src/components/Links/components/Link/components/ExploreViewLink/exploreViewLink.tsx, src/components/Links/components/Link/link.tsx, src/components/common/Button/components/CallToActionButton/callToActionButton.tsx, src/components/common/Button/components/HelpIconButton/helpIconButton.tsx, src/components/common/Card/components/CardActionArea/cardActionArea.tsx, src/components/common/Socials/socials.tsx, src/hooks/useMenuWithPosition.ts, src/theme/common/components.ts, types/data-explorer-ui.d.ts
=> fix: nested header navigation style updates and improve change in navigation selection (#139)

src/components/Layout/components/ContentLayout/contentLayout.styles.ts, src/components/Layout/components/ContentLayout/contentLayout.tsx, src/components/Layout/components/Sidebar/components/SidebarPositioner/sidebarPositioner.styles.ts, src/components/Layout/components/Sidebar/sidebar.styles.ts
=> fix: entity list view should show footer when content in side bar and table is not scrollable (#144)

src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/FormStep/components/ConnectTerraToNIHAccount/connectTerraToNIHAccount.tsx
=> feat: update export set up form nih tutorial link (#156)

src/components/Layout/components/Header/components/Content/components/Actions/components/Search/components/SearchBar/common/utils.ts
=> fix: fix typescript error usesearchparams returns readonlyurlsearchparams | null with pages (#154)

src/providers/authentication.tsx
=> fix: fix authentication provider default value for isenabled (#159)

src/components/Layout/components/Header/components/Content/components/Navigation/navigation.styles.ts
=> fix: right header navigation position (#167)

src/components/Layout/components/Header/components/Content/components/Actions/actions.styles.ts
=> fix: fix right side header navigation position (#184)

src/common/analytics/readme-analytics.md
Closes #174.
Added documentation of each GA4 event in `src/common/analytics/events.ts` in `readme-analytics.md`
=> docs: added analytics readme (#174)

package-lock.json, package.json, src/apis/azul/common/constants.ts, src/components/Index/components/AzulFileDownload/azulFileDownload.tsx, src/components/Index/components/AzulFileDownload/common/constants.ts, src/hooks/useFileLocation.ts, src/utils/tests.ts, tests/azulFileDownload.test.tsx, tests/useFileLocation.test.ts
=> fix: fix azul file download component (#196)

package-lock.json
Closes #199.
- `npm audit` resolved security warnings; 0 vulnerabilities.
- `jest` tests pass.
=> chore: address npm secuirty warnings (#199)

src/components/Layout/components/Header/common/entities.ts, src/components/Layout/components/Header/common/utils.ts, src/components/Layout/components/Header/hooks/useHeaderVisibility.ts
=> feat: make socials visibility configurable (#204)

src/components/common/Markdown/markdown.tsx
=> fix: fix markdown component text overflow (#209)

src/components/Index/components/Hero/components/ExportButton/exportButton.tsx
- Added a tracking id `button-cohort-export` to the `ExportButton` component
=> chore: added tracking id to ExportButton component (#218)

package-lock.json, package.json
=> fix!: fix mui error "cannot resolve @mui/utils/getReactNodeRef" (#242)

src/components/types.ts, src/theme/common/types.ts
=> feat: add 'testid' prop interface (#247)

src/components/Layout/components/Footer/components/VersionInfo/constants.ts, src/components/Layout/components/Footer/components/VersionInfo/versionInfo.tsx, src/components/Layout/components/Footer/footer.tsx, src/components/utils.ts
=> fix: access NEXT_PUBLIC environment variables directly from the environment (#272)

src/components/Layout/components/Footer/components/VersionInfo/versionInfo.styles.ts, src/config/utils.ts, src/providers/config.tsx
=> fix: centre alignment of version info and update Config Provider entity list as optional (#275)

src/components/Table/common/utils.ts
=> fix: quote values in tsv export when they contain syntactic characters (#314)

src/components/Support/components/ViewSupport/types.ts, src/components/Support/components/ViewSupport/viewSupport.tsx
=> fix: add 'rel' attribute to viewsupport component props (#328)

src/components/DataDictionary/components/Entities/constants.ts, src/components/DataDictionary/components/Entities/entities.tsx, src/components/DataDictionary/components/Entities/types.ts, src/components/DataDictionary/components/Entity/constants.ts, src/components/DataDictionary/components/Entity/entity.tsx, src/components/DataDictionary/components/Entity/types.ts, src/components/DataDictionary/components/Table/columns/columnDef.ts, src/components/DataDictionary/components/Table/columns/columnIdentifier.ts, src/components/DataDictionary/components/Table/columns/types.ts, src/components/DataDictionary/components/Table/components/BasicCell/basicCell.tsx, src/components/DataDictionary/components/Table/components/BasicCell/types.ts, src/components/DataDictionary/components/Table/hook.ts, src/components/DataDictionary/components/Table/options/core/constants.ts, src/components/DataDictionary/components/Table/options/hook.ts, src/components/DataDictionary/components/Table/options/sorting/constants.ts, src/components/DataDictionary/components/Table/table.styles.ts, src/components/DataDictionary/components/Table/table.tsx, src/components/DataDictionary/components/Table/types.ts, src/components/DataDictionary/dataDictionary.styles.ts, src/components/DataDictionary/dataDictionary.tsx, src/components/DataDictionary/hooks/UseDataDictionary/hook.ts, src/components/DataDictionary/hooks/UseDataDictionary/types.ts, src/styles/common/mui/typography.ts, src/views/DataDictionaryView/dataDictionaryView.tsx
=> feat: create data dictionary table component (#334)

src/components/DataDictionary/components/Entity/entity.tsx, src/components/DataDictionary/components/Table/components/BasicCell/basicCell.tsx, src/components/Login/components/Section/components/Warning/warning.tsx, src/components/Table/components/TableCell/components/RowPositionCell/constants.ts, src/components/common/LoginDialog/constants.ts, src/styles/common/mui/typography.ts
=> refactor!: refactor typography constants (#339)

src/common/selectors.ts, src/components/Filter/components/SearchAllFilters/searchAllFilters.tsx, src/components/Layout/components/Footer/footer.tsx, src/components/Layout/components/Header/header.tsx, src/components/Layout/components/Sidebar/components/SidebarPositioner/sidebarPositioner.tsx
=> refactor!: refactor selectors into an enum and add ids to header and footer (#341)

.storybook/preview.js, jest.config.js, src/components/common/Form/components/Select/select.tsx, src/storybook/decorators.tsx, src/storybook/parameters.ts, src/theme/common/components.ts, tests/setup.ts
=> fix: jest tests missing storybook annotations (#354)

src/styles/common/mui/typography.ts, src/theme/common/typography.ts, src/theme/theme.ts, types/data-explorer-ui.d.ts
=> feat: add 'text-heading-xsmall' to typography variants (#361)

src/components/Stepper/components/Step/components/StepContent/stepContent.styles.ts, src/components/Stepper/components/Step/components/StepContent/stepContent.tsx, src/components/Stepper/components/Step/components/StepLabel/components/Label/components/Icon/stories/icon.stories.tsx, src/components/Stepper/components/Step/components/StepLabel/stories/stepLabel.stories.tsx, src/components/Stepper/components/Step/constants.ts, src/components/Stepper/components/Step/step.styles.ts, src/components/Stepper/components/Step/step.tsx, src/components/Stepper/components/Step/stories/contants.ts, src/components/Stepper/components/Step/stories/step.stories.tsx, src/storybook/controls/constants.ts, src/storybook/controls/types.ts, src/storybook/controls/utils.ts, src/storybook/loremIpsum.ts, src/styles/common/mui/stepper.ts
=> feat: create step component (#364)

tests/setup.ts
=> fix: fix ci test failure 'textencoder is not defined' (#381)

package-lock.json, package.json, src/components/DataDictionary/components/Entities/constants.ts, src/components/DataDictionary/components/Entities/entities.tsx, src/components/DataDictionary/components/Entity/constants.ts, src/components/DataDictionary/components/Entity/entity.tsx, src/components/Login/components/Section/components/Consent/consent.styles.ts, src/components/Login/components/Section/components/Consent/consent.tsx, src/components/Login/components/Section/components/Consent/types.ts, src/components/Stepper/components/Step/components/StepContent/stepContent.styles.ts, src/components/Stepper/components/Step/components/StepContent/stepContent.tsx, src/components/common/LoginDialog/loginDialog.styles.ts, src/theme/common/typography.ts, types/data-explorer-ui.d.ts
=> chore!: update mui to latest version v7 (#373)

src/components/Layout/components/Header/components/Content/components/Actions/components/Search/components/SearchBar/searchBar.styles.ts, src/components/Layout/components/Header/components/Content/components/Actions/components/Search/components/SearchBar/searchBar.tsx
=> fix: fix search bar position when a banner is displayed (#369)

src/components/Filter/components/FilterLabel/filterLabel.tsx, src/components/Filter/components/SearchAllFiltersSearch/components/SearchCloseButton/searchCloseButton.tsx, src/components/Layout/components/Header/components/Content/components/Actions/components/Authentication/authentication.tsx, src/components/Layout/components/Header/components/Content/components/Actions/components/Menu/components/Toolbar/toolbar.tsx, src/components/Layout/components/Header/components/Content/components/Actions/components/Menu/menu.tsx, src/components/Layout/components/Header/components/Content/components/Actions/components/Search/components/SearchBar/searchBar.tsx, src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationDrawer/navigationDrawer.tsx, src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationMenu/navigationMenu.tsx, src/components/Layout/components/Sidebar/components/SidebarButton/sidebarButton.tsx, src/components/Support/components/SupportRequest/components/Dialog/dialog.tsx, src/components/Table/components/Pagination/pagination.tsx, src/components/Table/components/TableHead/tableHead.tsx, src/components/common/AnchorLink/anchorLink.tsx, src/components/common/Breadcrumbs/breadcrumbs.tsx, src/components/common/Button/components/DropdownButton/dropdownButton.tsx, src/components/common/Button/components/NavigationButton/navigationButton.tsx, src/components/common/CopyToClipboard/copyToClipboard.tsx, src/components/common/Dialog/components/DialogTitle/dialogTitle.tsx, src/components/common/Drawer/components/DrawerTitle/drawerTitle.tsx, src/components/common/Form/components/Select/components/DropDownIcon/dropDownIcon.tsx, src/components/common/Form/components/UploadFile/uploadFile.tsx, src/components/common/Section/components/CollapsableSection/collapsableSection.tsx
=> fix: fix Jest ESM Transformation Issue for @mui/icons-material (#352)

src/components/Export/components/ExportToTerra/components/TerraSetUpForm/components/NIHAccountExpiryWarning/nihAccountExpiryWarning.tsx
=> fix: update 'renew your account' link (#385)

src/theme/theme.ts
=> fix: fix theme with deepmerge (#399)

src/components/Filter/components/ClearAllFilters/clearAllFilters.tsx, src/components/Filter/components/Filter/filter.tsx, src/components/Filter/components/Filters/filters.tsx, src/components/Filter/components/HighlightedLabel/highlightedLabel.tsx, src/components/Filter/components/SearchAllFilters/components/VariableSizeListItem/variableSizeListItem.tsx, src/components/Filter/components/SearchAllFilters/searchAllFilters.tsx, src/components/Filter/components/VariableSizeListItem/variableSizeListItem.tsx, src/components/Index/components/EntitiesView/constants.ts, src/components/Index/components/EntitiesView/entitiesView.tsx, src/components/Index/components/EntitiesView/types.ts, src/components/Index/components/Hero/components/ExportButton/exportButton.tsx, src/components/Layout/components/Sidebar/components/SidebarDrawer/sidebarDrawer.tsx, src/components/Layout/components/Sidebar/sidebar.tsx, src/components/Table/components/Pagination/pagination.tsx, src/components/Table/components/PaginationSummary/paginationSummary.tsx, src/components/Table/components/TableRows/tableRows.tsx, src/tests/testIds.ts, src/views/ExploreView/exploreView.tsx, tests/entitiesView.test.tsx
=> feat: add test ids to key testable components (#401)

src/components/Login/components/Button/constants.ts, src/components/common/Button/constants.ts, src/styles/common/mui/button.ts
=> refactor!: refactor button constants (#405)

src/components/Filter/components/FilterRange/constants.ts, src/components/Filter/components/FilterRange/filterRange.styles.ts, src/components/Filter/components/FilterRange/filterRange.tsx, src/components/Filter/components/FilterRange/hooks/UseFilterRange/hook.ts, src/components/Filter/components/FilterRange/hooks/UseFilterRange/types.ts, src/components/Filter/components/FilterRange/stories/filterRange.stories.tsx, src/components/Filter/components/FilterRange/types.ts, src/tests/mui/constants.ts, src/tests/testIds.ts, tests/filterRange.test.tsx, tests/filterRangeMock.test.tsx
=> feat: range filter component (#397)

src/components/Index/components/EntitiesView/components/ChartView/components/Chart/barX/plot.ts, src/components/Index/components/EntitiesView/components/ChartView/components/Chart/barX/utils.ts, src/components/Index/components/EntitiesView/components/ChartView/components/Chart/stories/chart.stories.tsx, src/components/Index/components/EntitiesView/components/ChartView/stories/chartView.stories.tsx, tests/chart.test.tsx
=> feat: chart view - sort bars by size - largest first (#409)

src/components/Index/components/EntitiesView/components/ChartView/chartView.tsx, src/components/Index/components/EntitiesView/components/ChartView/stories/args.ts, src/components/Index/components/EntitiesView/components/ChartView/types.ts, src/views/ExploreView/exploreView.tsx, tests/chartView.test.tsx
=> feat: chart view - update titles to show the entity type (#412)

src/common/entities.ts
=> fix: make gridtracksize import relative (#434)

src/common/entities.ts
=> fix!: updated column def width type #437

src/common/entities.ts, src/components/DataDictionary/common/utils.ts, src/components/DataDictionary/components/Entities/entities.tsx, src/components/DataDictionary/components/Entities/types.ts, src/components/DataDictionary/components/Entity/entity.tsx, src/components/DataDictionary/components/Entity/types.ts, src/components/DataDictionary/components/Outline/utils.ts, src/components/DataDictionary/components/Table/components/BasicCell/types.ts, src/components/DataDictionary/components/Table/hook.ts, src/components/DataDictionary/hooks/UseDataDictionary/types.ts
#423
* Updated modeling of data dictionary and related entities to handle larger set of specifications.
=> feat!: updated data dictionary model #423

src/common/entities.ts
#423
* Updated data dictionary prefix, annotations, and description to be optional.
=> fix: updated optional dictionary values #423

src/common/entities.ts
=> fix: updated ColumnDef typing #423

src/components/Filter/components/views/select/SelectListItem/selectListItem.tsx, src/components/Filter/components/views/select/SelectListItem/types.ts, src/components/Filter/components/views/select/components/Checkbox/checkbox.tsx, src/components/Filter/components/views/select/components/ListItemButton/listItemButton.styles.ts, src/components/Filter/components/views/select/components/ListItemButton/listItemButton.tsx, src/components/Filter/components/views/select/components/ListItemText/components/Count/count.tsx, src/components/Filter/components/views/select/components/ListItemText/components/Term/term.tsx, src/components/Filter/components/views/select/components/ListItemText/listItemText.styles.ts, src/components/Filter/components/views/select/components/ListItemText/listItemText.tsx, src/components/Table/components/TableFeatures/ColumnFilter/columnFilter.tsx, src/utils/typeGuards.ts
Closes #595.
This pull request introduces a reusable `SelectListItem` component and updates the `ColumnFilter` component to leverage it. The changes focus on improving code reusability, maintainability, and consistency in the UI. Key updates include the creation of new components, styling enhancements, and refactoring of the `ColumnFilter` logic.
* **`SelectListItem` Component**: Added a new reusable component combining `Checkbox`, `ListItemButton`, and `ListItemText` for consistent rendering of selectable list items. (`src/components/Filter/components/views/select/SelectListItem/selectListItem.tsx`, [src/components/Filter/components/views/select/SelectListItem/selectListItem.tsxR1-R19](diffhunk://#diff-31ac1f3bde70bd4089b21979fdfb0cb0953060306c05fc2ed1be9e25a35bcdc5R1-R19))
* …
=> feat: create select filter item component (#595)

src/components/Filter/components/adapters/tanstack/ColumnFiltersAdapter/columnFiltersAdapter.tsx, src/components/Filter/components/adapters/tanstack/ColumnFiltersAdapter/hooks/UseUpdateFilterSort/hook.ts, src/components/Filter/components/adapters/tanstack/ColumnFiltersAdapter/hooks/UseUpdateFilterSort/types.ts, src/components/Filter/components/adapters/tanstack/ColumnFiltersAdapter/hooks/UseUpdateFilterSort/utils.ts, src/components/Filter/components/adapters/tanstack/ColumnFiltersAdapter/types.ts, src/components/Filter/components/adapters/tanstack/ColumnFiltersAdapter/utils.ts, src/components/Filter/components/controls/Controls/components/FilterSort/filterSort.tsx, src/components/Filter/components/controls/Controls/components/FilterSort/types.ts, src/components/Filter/components/controls/Controls/controls.styles.ts, src/components/Filter/components/controls/Controls/controls.tsx, src/components/Filter/components/controls/Controls/types.ts, src/components/Filter/components/surfaces/types.ts
Closes #647.
This pull request introduces a new feature that allows users to sort filter values in the filter UI, either alphabetically or by count. The implementation adds state management, UI controls, and utilities to support this filter sorting capability. The changes touch multiple files to propagate the new functionality from the table meta, through the adapter, and into the filter controls and UI.
The most important changes are:
**Filter Sort Feature Implementation:**
* Added the `useUpdateFilterSort` hook with supporting types and utilities to manage the filter sort state, determine if sorting is enabled, and handle user changes. (`hook.ts`, `types.ts`, `utils.ts`) [[1]](diffhunk://#diff-ae69f84133ee5371ee5bb471c1ec9653faf84e790fd515bcdb4c03af0ffae51cR1-R22) …
=> feat: configure filter sort for tanstack column filtering (#647)

src/components/Table/components/TableFeatures/TableDownload/tableDownload.styles.ts, src/components/Table/components/TableFeatures/TableDownload/tableDownload.tsx, src/components/Table/components/TableFeatures/TableDownload/types.ts
=> feat: create download button (#651)
