- src/providers/exploreState.tsx
- src/providers/exploreState/utils.ts
Closes #60.
- Explore State Action `ClearFilters` fixes clear all filters button for the entity list.
- Explore State Action `SelectEntityType` updates state values for the selected tab such as `categoryViews` and `categoryGroupConfigs`.
- Explore State Actions `ProcessExploreResponse`, `UpdateFilter`, `UpdateSorting`, and `UpdateColumnVisibility` use the new `updateEntityPageState` function to update the `entityPageState`.
- Initialisation of Explore State fixes the `entityPageState` - the current entity list's `entityPageState`'s `filterState` and `filterCount` are initialised by values from the decoded filter param.
> fix: fix explore state actions initial explore state filters and the clear filters action (#60)

- src/components/Table/components/TableToolbar/components/RowPreview/components/RowDrawer/common/constants.ts
- src/components/Table/components/TableToolbar/components/RowPreview/components/RowDrawer/rowDrawer.tsx
- src/components/Table/components/TableToolbar/components/RowPreview/components/Section/components/RowDetail/rowDetail.tsx
- src/components/Table/components/TableToolbar/components/RowPreview/rowPreview.tsx
- src/config/entities.ts
> feat: update row preview component response props to row data (#117)

- src/components/Layout/components/Header/common/entities.ts
- src/components/Layout/components/Header/components/Content/components/Navigation/common/utils.ts
- src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationMenuItems/navigationMenuItems.tsx
- src/components/Layout/components/Header/components/Content/components/Navigation/navigation.tsx
> fix: active header navigation links should have the option to be matched by "exact" (#141)

- src/components/Links/common/utils.ts
- src/components/Links/components/Link/link.tsx
> feat: link component internal url test should include hash routes (#147)

- src/components/Layout/components/Header/components/Content/components/Actions/components/Search/components/SearchBar/common/constants.ts
- src/components/Layout/components/Header/components/Content/components/Actions/components/Search/components/SearchBar/common/utils.ts
- src/components/Layout/components/Header/components/Content/components/Actions/components/Search/components/SearchBar/searchBar.tsx
> feat: update search bar redirect to allow for an internal link (#149)

- src/components/Layout/components/Header/common/entities.ts
- src/components/Layout/components/Header/common/utils.ts
- src/components/Layout/components/Header/components/Content/components/Actions/components/Menu/menu.tsx
- src/components/Layout/components/Header/components/Content/components/Navigation/common/utils.ts
- src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationDrawer/navigationDrawer.tsx
- src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationMenu/navigationMenu.tsx
- src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationMenuItems/navigationMenuItems.tsx
- src/components/Layout/components/Header/components/Content/components/Navigation/navigation.tsx
- src/components/Layout/components/Header/header.stories.tsx
- src/components/Layout/components/Header/header.tsx
- src/components/Layout/components/Header/hooks/useHeaderNavigation.ts
- src/components/Layout/components/Header/hooks/useHeaderVisibility.ts
- src/components/Layout/components/Header/hooks/useMenu.ts
- src/components/common/Dialog/hooks/useDialog.ts
- src/components/common/Menu/hooks/useMenu.ts
> fix: fix header navigation active nested menu highlight (#167)

- src/components/Filter/components/Filter/filter.styles.ts
- src/components/Filter/components/Filter/filter.tsx
- src/components/Filter/components/FilterLabel/filterLabel.stories.tsx
- src/components/Filter/components/FilterLabel/filterLabel.styles.ts
- src/components/Filter/components/FilterLabel/filterLabel.tsx
- src/components/Filter/components/FilterTags/filterTags.styles.ts
- src/components/Filter/components/Filters/filters.styles.ts
- src/components/Filter/components/Filters/filters.tsx
> feat: update filter ui and hover state (#165)

- src/utils/replaceParameters.ts
> feat: add replaceparameters function (#158)

- src/common/analytics/entities.ts
- src/components/Export/common/tracking.ts
#213 
- Removed `entity_type` parameter from the model for the `bulk_download_requested` GA4 event, since it returned a hardcoded value
> chore: removed entity_type parameter from bulk_download_requested event

- src/components/Export/components/ExportMethod/exportMethod.tsx
Track clicks to the `ExportMethod` buttons, with different events depending on the button
- Added an optional prop to `ExportMethod` add a id for tracking purposes
- Added the tracking id to the invocation of `ExportButton` in `ExportMethod`
> chore: added optional id to ExportMethod buttons (#217)

- src/common/analytics/readme-analytics.md
- src/components/Support/components/SupportRequest/components/SupportRequestForm/supportRequestForm.tsx
- Added a tracking id as specified in https://github.com/DataBiosphere/data-browser/issues/4188 to the submit button in `SupportRequestForm`
- Updated `readme-analytics.md` to document tracking IDs
> Add tracking to SupportRequestForm

- src/components/Index/components/TitleCell/titleCell.tsx
- src/components/Layout/components/Header/components/Content/components/Logo/logo.styles.ts
- src/components/Layout/components/Header/components/Content/components/Logo/logo.tsx
- src/components/Links/components/Link/link.tsx
- src/components/common/Banner/components/BannerPrimary/bannerPrimary.styles.ts
- src/components/common/Banner/components/CookieBanner/cookieBanner.styles.ts
- src/components/common/Banner/components/CookieBanner/cookieBanner.tsx
- src/components/common/Breadcrumbs/breadcrumbs.tsx
- src/theme/common/components.ts
- src/theme/common/types.ts
> feat: update mui link theme styles (#245)

- src/common/analytics/entities.ts
- src/common/analytics/readme-analytics.md
- src/components/Export/common/tracking.ts
- src/components/Export/components/DownloadCurlCommand/downloadCurlCommand.tsx
- src/components/Export/components/ExportToTerra/exportToTerra.tsx
- src/components/Export/components/ManifestDownload/manifestDownload.tsx
- Added event models as follows:
- Add the following event models
- `index_analyze_in_terra_requested`
- `entity_name`
- `index_file_manifest_requested`
- `entity_name`
- Alter the existing `bulk_download_requested` model as follows
-  Remove params for `catalog` and `current_query`
-  Rename `index` to `entity_name`
- Called events on clicking the request button
- Documented changes in `readme-analytics.md`
> feat: added and updated index export tracking (#222)

- src/components/Layout/components/Footer/components/VersionInfo/components/Tooltip/components/Title/constants.ts
- src/components/Layout/components/Footer/components/VersionInfo/components/Tooltip/components/Title/title.tsx
- src/components/Layout/components/Footer/components/VersionInfo/components/Tooltip/components/Title/utils.ts
- src/components/Layout/components/Footer/components/VersionInfo/constants.ts
- src/components/Layout/components/Footer/components/VersionInfo/types.ts
- src/components/Layout/components/Footer/components/VersionInfo/utils.ts
- src/components/Layout/components/Footer/components/VersionInfo/versionInfo.styles.ts
- src/components/Layout/components/Footer/components/VersionInfo/versionInfo.tsx
- src/components/Layout/components/Footer/footer.tsx
- src/components/Support/components/SupportRequest/components/Dialog/dialog.styles.ts
- src/components/Support/components/ViewSupport/viewSupport.styles.ts
- src/config/entities.ts
- src/styles/common/mui/chip.ts
- src/theme/common/components.ts
Closes #258.
- add constants
- `config.gitHubUrl`, and
- `config.layout.footer.versionInfo`
```
const BUILD_DATE = process.env.NEXT_PUBLIC_BUILD_DATE;
const GIT_HUB_REPO_URL = "https://github.com/DataBiosphere/data-browser";
const GIT_HASH = process.env.NEXT_PUBLIC_GIT_HASH;
const VERSION = process.env.NEXT_PUBLIC_VERSION;
```
```
versionInfo: C.VersionInfo({
versionInfo: {
buildDate: BUILD_DATE,
catalog,
gitHash: GIT_HASH,
version: VERSION,
},
}),
},
```
> feat: add optional version information to footer (#258)

- src/common/analytics/entities.ts
- src/components/Export/common/tracking.ts
- src/components/Export/components/DownloadCurlCommand/downloadCurlCommand.tsx
- src/components/Export/components/ExportToTerra/exportToTerra.tsx
- src/components/Export/components/ManifestDownload/manifestDownload.tsx
- src/components/Index/components/AzulFileDownload/azulFileDownload.tsx
- tests/azulFileDownload.test.tsx
- Added `file_downloaded` event and relevant models as specified in #260
- Added call to this event in `AzulFileDownload`, adding new optional props as needed
> feat!: added file download tracking (#260)

- src/components/common/Breadcrumbs/breadcrumbs.tsx
- src/components/common/Breadcrumbs/constants.ts
- src/styles/common/mui/link.ts
> feat: breadcrumbs should not inherit the new link style (#271)

- src/components/Layout/components/ContentLayout/contentLayout.styles.ts
- src/components/Layout/components/ContentLayout/contentLayout.tsx
- src/views/ContentView/contentView.tsx
> feat: update contentlayout to centre content when there is no navigation (#282)

- src/components/Links/components/Link/components/ExploreViewLink/exploreViewLink.tsx
Rather than accepting only URLs of the form `/[entityName]`, the link component, when passed an object for the URL, will accept URLs of the form`/.../[entityName]` (where `...` is any path)
> feat: allow url objects for explore links to have a path before the entity name (#291)

- src/common/constants.ts
- src/config/entities.ts
- src/hooks/useEntityExportConfig.ts
- src/views/EntityDetailView/entityDetailView.tsx
- src/views/EntityExportMethodView/entityExportMethodView.tsx
- src/views/EntityExportView/entityExportView.tsx
[Make the general and dataset-details Export panes consistent](https://github.com/DataBiosphere/data-browser/issues/4102)
* Updated entity config to allow for entity-specific exports and hiding tabs on detail pages.
* Added views and related functionality for rendering choose export and individual exports.
> feat: support unifying export views  #4102

- src/components/DataDictionary/components/Tooltip/components/Title/constants.ts
- src/components/DataDictionary/components/Tooltip/components/Title/title.tsx
- src/components/DataDictionary/components/Tooltip/components/Title/types.ts
- src/components/DataDictionary/components/Tooltip/constants.ts
- src/components/DataDictionary/components/Tooltip/tooltip.tsx
- src/components/DataDictionary/components/Tooltip/types.ts
Closes #317.
- Added MUI-based tooltip that takes two props: title and description.
- Component matches [mock](https://www.figma.com/design/JOUDXkKfgivRNFdBsWDPEH/AnVIL?node-id=8090-8475&t=ZpL4Obac6SeJyfCT-0).
```
<Tooltip description={description} title={title}><Button>Project Title</Button></Tooltip>
```
> feat: create data dictionary tooltip component (#317)

- src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationMenu/navigationMenu.tsx
- src/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationMenuItems/navigationMenuItems.tsx
- src/components/Layout/components/Header/components/Content/components/Navigation/constants.ts
- src/components/Layout/components/Header/components/Content/components/Navigation/navigation.tsx
- src/components/Layout/components/Header/header.tsx
Closes #297.
- Header navigation links (main navigation, menu navigation, and drawer navigation) all use anchor tags instead of buttons.
- The anchor tags include the relevant `rel` attribute for internal / external urls.
- The anchor tags include the `target` attribute, if configured, otherwise remain as `_self`.
- External links use `MuiLink` and internal links use Next's `Link` component.
- A test for the `Navigation` is advisable, however the component itself will need refactoring to handle recursion all in one file rather than having a parent ↔ child import cycle.
> feat: use anchor tags for all header and footer links (#297)

- src/providers/layoutDimensions/constants.ts
- src/providers/layoutDimensions/context.tsx
- src/providers/layoutDimensions/hook.ts
- src/providers/layoutDimensions/provider.tsx
- src/providers/layoutDimensions/types.ts
> feat: create a new provider that returns header and footer dimensions (#344)

- src/components/Layout/components/Outline/common/constants.ts
- src/components/Layout/components/Outline/components/ContentsTab/contentsTab.styles.ts
- src/components/Layout/components/Outline/components/ContentsTab/contentsTab.tsx
- src/components/Layout/components/Outline/components/ContentsTab/types.ts
- src/components/Layout/components/Outline/hooks/UseHash/hook.ts
- src/components/Layout/components/Outline/hooks/UseHash/types.ts
- src/components/Layout/components/Outline/hooks/UseTabs/constants.ts
- src/components/Layout/components/Outline/hooks/UseTabs/hook.ts
- src/components/Layout/components/Outline/hooks/UseTabs/utils.ts
- src/components/Layout/components/Outline/outline.styles.ts
- src/components/Layout/components/Outline/outline.tsx
- src/components/Layout/components/Outline/types.ts
- src/styles/common/mui/tab.ts
- src/styles/common/mui/tabs.ts
Closes #346.
- The `OutlineProps` have been moved to ./types and now extend Mui's `TabsProps`.
- A new hook, `useTabs`, has been introduced to manage Tabs state—built on existing component logic. Additionally, when the path changes, the update logic now checks if the selected entity is disabled; if so, it falls back to the default Tabs value.
> refactor!: refactor outline component with new hook handling state and disabled outline item (#346)

- src/components/Stepper/components/Step/components/StepIcon/stepIcon.stories.tsx
- src/components/Stepper/components/Step/components/StepIcon/stories/stepIcon.stories.tsx
- src/components/Stepper/components/Step/components/StepLabel/components/Label/components/Icon/constants.ts
- src/components/Stepper/components/Step/components/StepLabel/components/Label/components/Icon/icon.tsx
- src/components/Stepper/components/Step/components/StepLabel/components/Label/components/Icon/stories/contants.ts
- src/components/Stepper/components/Step/components/StepLabel/components/Label/components/Icon/stories/icon.stories.tsx
- src/components/Stepper/components/Step/components/StepLabel/components/Label/components/Icon/types.ts
- src/components/Stepper/components/Step/components/StepLabel/components/Label/constants.ts
- src/components/Stepper/components/Step/components/StepLabel/components/Label/label.styles.ts
- src/components/Stepper/components/Step/components/StepLabel/components/Label/label.tsx
- src/components/Stepper/components/Step/components/StepLabel/components/Label/stories/label.stories.tsx
- src/components/Stepper/components/Step/components/StepLabel/components/Optional/constants.ts
- src/components/Stepper/components/Step/components/StepLabel/components/Optional/optional.tsx
- src/components/Stepper/components/Step/components/StepLabel/constants.ts
- src/components/Stepper/components/Step/components/StepLabel/stepLabel.styles.ts
- src/components/Stepper/components/Step/components/StepLabel/stepLabel.tsx
- src/components/Stepper/components/Step/components/StepLabel/stories/contants.ts
- src/components/Stepper/components/Step/components/StepLabel/stories/stepLabel.stories.tsx
- src/storybook/controls/constants.ts
- src/storybook/controls/utils.ts
- src/storybook/loremIpsum.ts
- src/styles/common/mui/svgIcon.ts
- tests/stepIcon.test.tsx
Closes #360.
StepLabel component displays:
- A step indicator.
- A title, with optional tooltip.
- An optional sub-title (e.g. an ID or some extra info) when the step is completed.
Tests not required on this component.
> feat: create step label component (#360)

- src/storybook/parameters.ts
Closes #357.
Next.js's router is automatically stubbed for you so that when the router is interacted with, all of its interactions are automatically logged to the Actions panel if you have the Storybook actions addon. See [docs](https://storybook.js.org/docs/get-started/frameworks/nextjs#nextjs-routing).
[Default router configuration](https://storybook.js.org/docs/get-started/frameworks/nextjs#default-router) is provided by the `@storybook/nextjs` framework.
> refactor: storybook parameters nextjs router config (#357)

- src/components/Loading/loading.stories.tsx
- src/components/common/KeyValuePairs/components/KeyElType/keyElType.tsx
- src/components/common/KeyValuePairs/components/ValueElType/valueElType.tsx
Closes #367.
Fixes `KeyValuePairs` component `KeyElType` and `ValueElType` to enable updates to any Mui TypographyProp.
> fix!: fix keyvaluepairs component typography props (#367)

- src/components/common/Form/components/Select/select.tsx
- src/theme/common/components.ts
Tests pass with icon in Select default props in theme!
> fix: add dropdownicon to muiselect default props (#356)

- src/components/Support/components/SupportRequest/components/Dialog/dialog.styles.ts
- src/components/Support/components/ViewSupport/viewSupport.styles.ts
- src/styles/common/constants/shadows.ts
- src/styles/common/mixins/shadows.ts
- src/theme/common/components.ts
- src/theme/common/shadows.ts
- src/theme/theme.ts
Closes #417.
This pull request refactors the shadow system in the codebase to improve consistency and maintainability. The changes involve replacing individual shadow constants and methods with a centralized `SHADOWS` object, updating references across multiple files, and simplifying the theme configuration.
* Introduced a new `SHADOWS` object in `src/styles/common/constants/shadows.ts` to centralize shadow definitions.
* Removed individual shadow methods (`shadows01`, `shadows02`) from `src/styles/common/mixins/shadows.ts`.
* Replaced `shadows02` with `SHADOWS["02"]` in `dialog.styles.ts` and `viewSupport.styles.ts` for consistency. [[1]](diffhunk://#diff-d30a5e84a26608f710cace5d2f6b851a27a11d3528872afd64916b6c1ac287bfL15-R15) [[2]](diffhunk://#diff-997b3d142bab86b65d71669d2724da281f15391 …
> refactor!: add css shadow variables to theme (#417)

- src/components/Export/components/ExportMethod/exportMethod.tsx
- src/components/Login/components/Button/types.ts
- src/components/Login/components/Buttons/types.ts
- src/components/types.ts
- src/theme/common/entities.ts
Closes #420.
This pull request refactors type definitions and consolidates shared interfaces into a centralized `types` file, improving code organization and maintainability. The most important changes include introducing a new `TrackingProps` interface, updating component props to use centralized types, and removing redundant definitions.
* [`src/components/types.ts`](diffhunk://#diff-9b909becd3cda72d27670f588ebcdb1ffd0aac1f515343b0ca4e64071b9045c4R15-R18): Added a new `TrackingProps` interface to centralize the `trackingId` property.
* [`src/theme/common/entities.ts`](diffhunk://#diff-a13173e58a314ff0e66477a15ff1a7cec06c0839d473406b89ae36f7173b1d38L1-L7): Removed redundant `BaseComponentProps` and `TrackingComponentProps` interfaces, as they are now defined in `src/components/types.ts`. …
> refactor!: fix duplication of component type basecomponentprops (#420)

- src/components/Index/components/EntitiesView/components/ChartView/components/Chart/barX/constants.ts
- src/components/Index/components/EntitiesView/components/ChartView/components/Chart/barX/plot.ts
- src/components/Index/components/EntitiesView/components/ChartView/components/Chart/barX/utils.ts
- tests/chart.test.tsx
Closes #429.
This pull request introduces several changes to improve the chart rendering and its associated tests. Key updates include adjustments to chart layout constants, modifications to text rendering logic, and enhancements to test coverage for better validation of chart behavior.
* Updated `BAR_GAP` from `40` to `8` and introduced a new constant `MARGIN_LEFT` with a value of `136` in `barX/constants.ts`. These changes refine the spacing and alignment of chart elements. [[1]](diffhunk://#diff-f768cecbea466761e82e404aea54c227bb80be0ad185931255b43da4ad3fb039L1-R1) [[2]](diffhunk://#diff-f768cecbea466761e82e404aea54c227bb80be0ad185931255b43da4ad3fb039R11-R12)
* Adjusted `getPlotOptions` in `barX/plot.ts` to use `MARGIN_LEFT` for `marginLeft` and updated text rendering properties like …
> feat: update chart ui to make charts more compact (#429)

- tests/chart.test.tsx
Closes #432.
This pull request refactors the test code in `tests/chart.test.tsx` by introducing a helper function, `getLabelText`, to improve code readability and maintainability. The most important changes include replacing repeated logic with the new helper function and adding documentation for it.
* Replaced repeated logic for extracting and processing label text with a new helper function, `getLabelText`, in two test cases (`describe("Chart", () => {`) to simplify the code and reduce duplication. [[1]](diffhunk://#diff-314e8526e4dabc0d056025992274747d6491502e014a722fd6016799f0b6e2abL55-R55) [[2]](diffhunk://#diff-314e8526e4dabc0d056025992274747d6491502e014a722fd6016799f0b6e2abL77-R77)
* Introduced the `getLabelText` function, which retrieves and processes label text from an …
> refactor: chart test (#432)

- src/components/Index/components/EntitiesView/components/ChartView/components/Chart/barX/plot.ts
- src/components/Index/components/EntitiesView/components/ChartView/components/Chart/barX/utils.ts
- tests/chart.test.tsx
Closes #441.
This pull request introduces enhancements to the bar chart component by adding percentage-based count representations and updating related utility functions and tests. The most important changes include introducing new utility functions to calculate percentages and format count text, updating the chart rendering logic to include these enhancements, and modifying tests to validate the new functionality.
* Added `getCategoryTotalCount` and `getCountText` utility functions to calculate the total count of category values and format count text with percentages. These functions are now used in the chart rendering logic. (`src/components/Index/components/EntitiesView/components/ChartView/components/Chart/barX/utils.ts`, [[1]](diffhunk://#diff-b8103196bd657795227e29091770bbffe2a967887 …
> feat: chart view add percentage to counts (#441)

- src/components/Index/components/EntitiesView/components/ChartView/chartView.tsx
- tests/chartView.test.tsx
Closes #442.
This pull request updates the wording in the `ChartView` component and its associated test to improve clarity and consistency. The most important changes include modifying text displayed in the component and updating the test assertions to reflect the new wording.
**Text updates in the `ChartView` component:**
* [`src/components/Index/components/EntitiesView/components/ChartView/chartView.tsx`](diffhunk://#diff-fd62b377ad5ff710f43767b1cbd4077ab5799ed6efd6254daddc36b6d0d2b7cfL31-R31): Changed the text from "{entityName} per {label}" to "{entityName} by {label}" for better readability.
**Test updates for the `ChartView` component:**
* [`tests/chartView.test.tsx`](diffhunk://#diff-4930f91d268f85a2510ffd216d03579f92f761e32c3928cf9e22d9f61a969428L38-R38): Updated the regular …
> feat: chart view - change 'per' to 'by' in chart titles (#442)

- src/components/Index/components/EntitiesView/components/ChartView/components/Chart/barX/plot.ts
Closes #449.
This pull request introduces a minor update to the `getPlotOptions` function in `plot.ts`. Specifically, it adds a `type` property with the value `"band"` to the configuration object for improved chart rendering.
> fix: fix observable plot y-scale warning caused by numeric strings (#449)

- src/common/entities.ts
- src/components/DataDictionary/components/Table/components/BasicCell/basicCell.tsx
- src/components/DataDictionary/components/Table/components/BasicCell/types.ts
- src/components/Table/columnDef/accessorFn/typeGuards.ts
- src/components/Table/components/TableCell/components/ChipCell/chipCell.tsx
- src/theme/common/components.ts
Closes #451.
This pull request introduces several updates to enhance type flexibility, improve table cell components, and extend theming capabilities. The key changes include refactoring type definitions for attributes, updating table cell components to support generic types, and adding new variants to the `MuiChip` theme configuration.
* Refactored `AttributeValueTypes` to support generic types, making it more flexible for various use cases in `src/common/entities.ts`.
* Updated the `DataDictionaryColumnDef` interface to include optional properties for accessor function and cell renderer names, and modified the `width` property to support `GridTrackSize` types.
* Refactored `BasicCell` to use generic types and the `CellContext` type from `@tanstack/react-table`, improving type safety and …
> feat!: create data dictionary chip (#451)

- src/components/DataDictionary/dataDictionary.styles.ts
Closes #456.
This pull request updates the styling of the `View` component in the `dataDictionary.styles.ts` file to improve layout consistency and responsiveness. The most notable changes involve adjustments to the margins and removal of the `max-width` property.
Styling updates to `View` component:
* Changed the `margin` property from `0 auto` to `0 24px` for better alignment and spacing.
* Removed the `max-width` property to simplify layout constraints and ensure the component adapts dynamically to its container.
* Updated the `margin` property within the `mediaTabletDown` query from `0 auto` to `0 16px` to maintain consistent spacing on smaller screens.
> feat: update data dictionary view to be full width (#456)

- src/components/Table/components/TableCell/components/ChipCell/chipCell.tsx
Closes #471.
This pull request updates the `ChipCell` component to enhance type safety and flexibility by introducing a generic type constraint for `ChipProps`.
Type safety and flexibility improvements:
* [`src/components/Table/components/TableCell/components/ChipCell/chipCell.tsx`](diffhunk://#diff-419a745ebef4a83658b741e0839ceb051b914df69bf3d6c6ac7adc31a7d6f4c9L1-R8): Updated the `ChipCell` component to extend the `TValue` generic type from `ChipProps`, ensuring that the `getValue` function returns properties compatible with the `Chip` component.
> fix: update table chipcell component interface (#471)

- src/components/DataDictionary/components/Table/components/BasicCell/basicCell.tsx
- src/components/DataDictionary/components/Table/components/BasicCell/utils.ts
Closes #474.
This pull request refactors the `BasicCell` component in the `DataDictionary` table to improve type safety and enhance value rendering. The main changes include extending the `BasicCell` component's type definitions and introducing a utility function to handle value parsing.
* Updated the `BasicCell` component to extend the `TValue` type parameter, defaulting it to `ReactNode`, for improved type safety and flexibility. (`src/components/DataDictionary/components/Table/components/BasicCell/basicCell.tsx`, [src/components/DataDictionary/components/Table/components/BasicCell/basicCell.tsxR5-R17](diffhunk://#diff-3f04d2aba4efa174314604d83028ecc60a273fcbd9c78b81e8c4859d436296f3R5-R17))
* Replaced direct value rendering with a call to the newly introduced `parseValue` utility …
> fix: fix data dictionary basiccell component to render boolean values as string (#474)

- package-lock.json
- package.json
- src/components/Table/components/TableCell/components/LinkCell/linkCell.tsx
- src/components/Table/components/TableCell/components/LinkCell/stories/args.ts
- src/components/Table/components/TableCell/components/LinkCell/stories/linkCell.stories.tsx
- src/components/Table/components/TableCell/components/LinkCell/stories/types.ts
- src/components/Table/components/TableCell/components/LinkCell/utils.ts
- src/components/common/Link/typeGuards.ts
- src/theme/common/components.ts
- tests/linkCell.test.tsx
Closes #468.
This pull request introduces a new `LinkCell` component for rendering links in a table cell, along with supporting utilities, stories, and tests. The changes focus on adding functionality for client-side and external navigation, handling invalid links gracefully, and providing customization options.
* Added the `LinkCell` component to render links or fallback to plain text for invalid URLs, with support for client-side navigation using `next/link` (`src/components/Table/components/TableCell/components/LinkCell/linkCell.tsx`).
* Introduced utility functions (`getComponent`, `getRelAttribute`, `getTargetAttribute`) to determine the appropriate link component, `rel`, and `target` attributes based on navigation type (`src/components/Table/components/TableCell/components/LinkCell/u …
> feat!: create table cell for displaying links (#468)

- src/common/entities.ts
- src/components/DataDictionary/components/Entities/entities.tsx
- src/components/DataDictionary/components/Entities/types.ts
- src/components/DataDictionary/components/Entity/entity.tsx
- src/components/DataDictionary/components/Entity/types.ts
- src/components/DataDictionary/components/Outline/utils.ts
- src/components/DataDictionary/components/Table/hook.ts
- src/components/DataDictionary/components/Table/options/core/constants.ts
- src/components/DataDictionary/components/Table/options/hook.ts
- src/components/DataDictionary/components/Table/options/sorting/constants.ts
- src/components/DataDictionary/components/Table/table.tsx
- src/components/DataDictionary/components/Table/types.ts
- src/components/DataDictionary/dataDictionary.tsx
- src/components/DataDictionary/hooks/UseDataDictionary/hook.ts
- src/components/DataDictionary/hooks/UseDataDictionary/types.ts
- src/components/Table/components/TableCell/components/ChipCell/chipCell.tsx
- src/components/Table/components/TableCell/components/LinkCell/linkCell.tsx
Closes #476.
This pull request introduces a significant refactor to the data dictionary components, enabling support for generic row data types (`RowData`) across the system. The changes primarily focus on improving type safety, reusability, and extensibility by replacing hardcoded `Attribute` types with generics and updating related interfaces, components, and hooks accordingly.
* Updated the `Class` and `DataDictionary` interfaces in `src/common/entities.ts` to support generic row data types (`RowData`), making them more flexible and reusable. [[1]](diffhunk://#diff-55072a7254a52c5566b398a27313fb8df9f811f660083311d883d1beeb911d6cL44-R39) [[2]](diffhunk://#diff-55072a7254a52c5566b398a27313fb8df9f811f660083311d883d1beeb911d6cL65-R76)
* Removed the `AttributeValueTypes` type and replaced …
> feat!: make data dictionary config generic with attribute as default (#476)

- src/components/Index/index.tsx
- src/components/Index/table/hook.ts
- src/components/Index/table/types.ts
Closes #484.
This pull request introduces changes to the `useTable` hook in the `Index` component to support an `entityListType` parameter, enabling more flexible table configurations. The most important changes involve updating the `useTable` hook's signature, adding a new `UseTableProps` interface, and ensuring proper handling of `entityListType` in the hook's logic.
* **Added `entityListType` parameter to `useTable` hook**: The `useTable` hook now accepts an `entityListType` parameter via the new `UseTableProps` interface, allowing for more dynamic table behavior. (`[[1]](diffhunk://#diff-328057e5d539dd2de86abcc3770c26e51e260a9d60ac303ef6762193827d7584L43-R48)`, `[[2]](diffhunk://#diff-fa9bd9113a8581a6c793f6bb86ec6512d87498fe58b6296b93de80fe8aba78d6R6-R9)`)
* **Updated `useTable` …
> fix: prevent table column def and data mismatch for client side filtering (#484)

- src/providers/exploreState.tsx
Closes #486.
This pull request introduces a conditional update to the `exploreReducer` function in `src/providers/exploreState.tsx`. The update ensures that when the `payload.entityListType` matches the current `state.tabValue`, the filter count, filter state, and pagination state are reset appropriately. 
Key change:
* [`src/providers/exploreState.tsx`](diffhunk://#diff-e34f716996efb33d7b4fe80b9f5590e3cccedfb4e9027207e3c02641dd542e11R623-R629): Added logic to conditionally update `filterCount`, `filterState`, and `paginationState` when `payload.entityListType` matches `state.tabValue`. This helps maintain consistency in the state when switching between entity list types.
> fix: update explorestate provider updateentityfilters action: update filters when tabvalue matches entitylisttype (#486)

- src/providers/exploreState/hooks/UseBeforePopState/utils.ts
Fixes #491.
This pull request includes a minor change to the import paths in `src/providers/exploreState/hooks/UseBeforePopState/utils.ts` to use relative paths instead of module-alias paths.
Path adjustments:
* Updated the import paths for `SelectedFilter` and `SyncStateFromUrlPayload` to use relative paths, ensuring consistency and compatibility with the project's module resolution setup.
> fix: imports in usebeforepopstate utils (#491)

- src/common/categories/config/utils.ts
Closes #499.
This pull request includes a modification to the `findCategoryConfig` function in `src/common/categories/config/utils.ts` to enhance flexibility when matching configurations by allowing `viewKind` to be optional.
* Updated the function signature to allow `viewKind` to be optional by changing its type to `viewKind?: V`. This enables matching configurations where `viewKind` is undefined.
* Adjusted the predicate in the `configs.find` method to account for cases where `viewKind` is undefined, ensuring it matches configurations with `viewKind` explicitly set to `undefined` or matching the provided `viewKind`.
> fix: fix incorrect labels on filters (#499)

- src/common/entities.ts
- src/components/DataDictionary/dataDictionary.tsx
- src/components/DataDictionary/hooks/UseDataDictionary/hook.ts
- src/components/DataDictionary/hooks/UseDataDictionary/types.ts
- src/components/Layout/components/Header/header.styles.ts
This pull request introduces updates to the `DataDictionary` component and its related hooks, alongside a minor styling adjustment in the header component. The most significant changes include adding support for a `title` property in the `DataDictionary` component and updating the `annotations` type in the `Attribute` interface for greater flexibility.
* **Enhanced `annotations` type**: Updated the `annotations` field in the `Attribute` interface to use `Record<string, string | undefined>` for improved flexibility in handling mixed keys and optional values. (`src/common/entities.ts`)
* **Support for `title` property**: Added a `title` field to the `useDataDictionary` hook and propagated it through the `DataDictionary` component to allow dynamic titles. This includes changes to the …
> feat!: updated allowed annotation values #489

- src/providers/services/provider.tsx
- src/providers/services/wasPop/context.ts
- src/providers/services/wasPop/hook.ts
- src/providers/services/wasPop/provider.tsx
- src/providers/services/wasPop/types.ts
- src/services/beforePopState/popStateBus.ts
- src/services/beforePopState/types.ts
- src/services/beforePopState/useOnPopState.ts
- src/services/beforePopState/usePopStateBus.ts
Closes #509.
This pull request introduces a new navigation handling system that tracks browser back/forward navigation events and provides this state to components via context. The changes include creating a centralized pop-state event bus, a context provider for managing navigation state, and hooks for registering callbacks. These updates improve the application's ability to handle user-initiated navigation and provide consistent state management.
* [`src/providers/services/wasPop/context.ts`](diffhunk://#diff-85034b64986af3e4dbef824efe2276fdd433a5f78afdaaf379d054ab1f82afb5R1-R6): Added `WasPopContext` to provide a context for tracking whether navigation was triggered by a pop-state event.
* [`src/providers/services/wasPop/provider.tsx`](diffhunk://#diff-494b4ef7406ac84f882c40723308334a10 …
> feat: add global 'beforepopstate' bus to intercept browser back/forward navigation (#509)

- src/hooks/stateSyncManager/types.ts
This pull request introduces a small update to the `StateSyncManagerActions` interface in the `src/hooks/stateSyncManager/types.ts` file. The change adds a blank line for improved readability between interface definitions.
> refactor: linting (#510)

- src/providers/exploreState/initializer/utils.ts
Closes #517.
This pull request includes a small update to the `src/providers/exploreState/initializer/utils.ts` file. The change modifies the `query` property within the `initEntities` function to include an `entityListType` based on `entityPath` for better context initialization.
Fixes initialisation of the entities property in explore state!
> fix: fix explore state entity list type error (#517)

- src/components/Table/columnDef/globalFilter/filterFn.ts
- src/components/Table/columnDef/globalFilter/types.ts
- src/components/Table/columnDef/globalFilter/utils.ts
- src/components/Table/components/TableCell/components/RankedCell/rankedCell.tsx
- src/components/Table/components/TableCell/components/RankedCell/utils.ts
- src/theme/components/muiTableCell.ts
Closes #533.
This pull request introduces enhancements to the global filtering functionality in the table component, including support for ranking and highlighting matched cells based on search terms. The most significant changes involve updating the filtering logic, adding metadata for ranked columns, and implementing cell rendering with highlighted matches.
* [`src/components/Table/columnDef/globalFilter/filterFn.ts`](diffhunk://#diff-844b1fdd8aafc2a01cfe93f00a32fb56f2909bb601ffec796d9f8ab6e9a88440L1-R33): Updated the `fuzzy` function to rank other row columns for highlighting purposes and added support for filter metadata to track whether a column passed the filter.
* [`src/components/Table/columnDef/globalFilter/utils.ts`](diffhunk://#diff-e955bf6023442d6804bd1069f524ce6ef64fe85fde53af …
> feat: highlight global search text in table results (#533)

- src/components/DataDictionary/components/Filters/components/ColumnFilters/columnFilters.tsx
- src/components/DataDictionary/components/Filters/stories/filters.stories.tsx
- src/components/Table/components/TableFeatures/GlobalFilter/globalFilter.tsx
Closes #547.
This pull request introduces conditional rendering for column and global filters in the data dictionary and table components. The changes ensure that filters are only displayed when explicitly enabled via table options, improving flexibility and configurability.
* [`src/components/DataDictionary/components/Filters/components/ColumnFilters/columnFilters.tsx`](diffhunk://#diff-7943c2b249358bc0e5edadf255b893d21cfd0f83798359ec50fc17b2b83625faL11-R17): Updated the `ColumnFilters` component to return `null` if `enableColumnFilters` is not enabled in the table options, preventing unnecessary rendering.
* [`src/components/Table/components/TableFeatures/GlobalFilter/globalFilter.tsx`](diffhunk://#diff-6c6680038054ca9efe9c6bd2a8c5c85bb4d1663957b87eee90198229c4eee348L13-R19): Modified …
> feat: hide global filtering search bar when global filters are disabled (#547)

- src/components/Export/components/ExportSummary/components/ExportSelectedDataSummary/exportSelectedDataSummary.tsx
- src/components/Index/components/EntityView/components/layout/Summary/summary.tsx
- src/tests/testIds.ts
Closes #557.
This pull request introduces new test IDs to improve the ability to identify and interact with specific components during testing. The changes primarily involve adding `data-testid` attributes to key components and updating the `TEST_IDS` object to define these new IDs.
* [`src/components/Export/components/ExportSummary/components/ExportSelectedDataSummary/exportSelectedDataSummary.tsx`](diffhunk://#diff-8bd4a43d8b3b8104301743440d6fa6f5360a95f70585a85ff59f5cf223ba2484L20-R21): Added a `data-testid` attribute (`TEST_IDS.EXPORT_SUMMARY`) to the `GridPaperSection` component to facilitate testing of the export summary section.
* [`src/components/Index/components/EntityView/components/layout/Summary/summary.tsx`](diffhunk://#diff-45488f7ea6441ab76b1b82f8a7226c9ca6e47c8db509514e950c …
> feat: add data test id to summary (#557)

- src/components/DataDictionary/components/Table/options/expanded/constants.ts
- src/components/Detail/components/Table/components/TableRows/tableRows.tsx
- src/components/Links/components/Link/components/ExploreViewLink/exploreViewLink.tsx
- src/components/Links/components/Link/link.tsx
- src/components/MarkdownRenderer/components/Anchor/anchor.tsx
- src/components/Table/components/TableCell/components/LinkCell/linkCell.tsx
- src/components/Table/components/TableCell/components/RowSelectionCell/rowSelectionCell.tsx
- src/components/Table/components/TableFeatures/RowExpanding/utils.ts
- src/components/Table/components/TableRow/tableRow.styles.ts
- src/components/Table/components/TableRows/tableRows.tsx
Closes #569.
This pull request introduces functionality to support expandable table rows in the application. Key changes include adding the ability to toggle row expansion, updating styles for expandable rows, and ensuring proper integration with existing table components.
* Added a utility function `handleToggleExpanded` in `src/components/Table/components/TableFeatures/RowExpanding/utils.ts` to manage the logic for toggling the expanded state of rows, including checks for grouping and text selection.
* Updated the `EXPANDED_OPTIONS` object in `src/components/DataDictionary/components/Table/options/expanded/constants.ts` to include `getRowCanExpand`, enabling the expansion feature.
* Modified `TableRows` components in `src/components/Detail/components/Table/components/TableRows/tableRows. …
> feat: add table row expansion to table components (#569)

- src/components/DataDictionary/components/Filters/components/ColumnFilters/columnFilters.styles.ts
- src/components/DataDictionary/components/Filters/filters.styles.ts
- src/components/DataDictionary/components/Layout/components/EntitiesLayout/entitiesLayout.styles.ts
- src/components/DataDictionary/components/Layout/components/FiltersLayout/filtersLayout.styles.ts
- src/components/DataDictionary/components/Layout/components/OutlineLayout/outlineLayout.styles.ts
- src/components/DataDictionary/components/Layout/components/TitleLayout/titleLayout.styles.ts
- src/components/DataDictionary/components/Title/title.styles.ts
- src/components/DataDictionary/dataDictionary.styles.ts
- src/styles/common/mixins/breakpoints.ts
Closes #583.
This pull request focuses on updating the breakpoint mixins used across various styled components to improve responsiveness and maintain consistency. The most important changes include replacing the `mediaTabletDown` mixin with newly introduced `bpDown820` and `bpDown1024` mixins, as well as introducing new breakpoints in the `breakpoints.ts` file.
* [`src/styles/common/mixins/breakpoints.ts`](diffhunk://#diff-e6335f24e1ea71e29585444daf18b0bb2b7cb9eacddacbae7e39636a5fcd8856R4-R9): Added `bpDown820` and `bpDown1024` mixins for more precise control over responsive design.
* **Switch to `bpDown820`:**
- [`src/components/DataDictionary/components/Filters/components/ColumnFilters/columnFilters.styles.ts`](diffhunk://#diff-bac17e62cc809a4487b1dce8b1c83b3904b9f43c0e291bb89db918e0df9f …
> feat: update data dictionary smaller viewport navigation and search bar layouts (#583)

- src/components/common/Drawer/provider/provider.tsx
- src/components/common/Drawer/provider/types.ts
Closes #585.
This pull request refactors the `DrawerProvider` component to improve type safety and enhance flexibility in how children are rendered. The key changes include introducing a new `DrawerProviderProps` type and updating the `DrawerProvider` implementation to support function-based children.
* [`src/components/common/Drawer/provider/types.ts`](diffhunk://#diff-6ffce666dcb687e6bb3ba63ec2c3ff675eb4e89c9f4ad7ddc07edf1c742e9c1cR2-R12): Added a new `DrawerProviderProps` type, which allows `children` to be either a `ReactNode` or a function that receives `DrawerContextProps` as an argument and returns a `ReactNode`.
* [`src/components/common/Drawer/provider/provider.tsx`](diffhunk://#diff-7cfc88fd9753f71b26690f991ac965e62c193d52076e76e47948220ecef0f257L1-R16): Updated the …
> refactor: drawerprovider to expose onClose via render prop (#585)

- src/components/DataDictionary/components/Description/description.styles.ts
- src/components/DataDictionary/components/Description/description.tsx
- src/components/DataDictionary/components/Entity/entity.styles.ts
- src/components/DataDictionary/components/Layout/components/FiltersLayout/filtersLayout.styles.ts
- src/components/DataDictionary/components/Layout/components/TitleLayout/titleLayout.styles.ts
- src/components/DataDictionary/components/Table/table.styles.ts
- src/components/DataDictionary/components/Table/table.tsx
- src/components/DataDictionary/dataDictionary.styles.ts
- src/components/Detail/components/Table/components/TableRows/components/CollapsableRows/collapsableRows.tsx
Closes #600.
This pull request introduces several updates to the `DataDictionary` components, focusing on replacing the `RoundedPaper` component with `FluidPaper`, improving responsiveness with new breakpoints, and refining table behavior. Below is a summary of the most important changes grouped by theme:
* Replaced `RoundedPaper` with `FluidPaper` across multiple components (`Description`, `Table`) to align with updated design standards. (`[[1]](diffhunk://#diff-a61d82df2129617b1a4046c9f7073ad0e07024de4e8900efc72931e6a7a2aebeL8-R11)`, `[[2]](diffhunk://#diff-a9505d30e1a9ffea36dc62258bd8018130614d4565d13a93619f594aac8e2785L2-R12)`, `[[3]](diffhunk://#diff-9730880f6a7cfb16530f6ce6e5817b00b016d55700395c0d7a0eb23434f32cf7L3-R5)`, `[[4]](diffhunk://#diff-4764775786fddeeb789131b5732379710f66adb …
> feat: make data dictionary table row-collapse for smaller viewports (#600)

- src/components/DataDictionary/components/Filters/components/ColumnFilters/columnFilters.tsx
- src/components/Table/components/TableFeatures/ColumnFilter/columnFilter.tsx
- src/theme/common/components.ts
Closes #603.
This pull request introduces enhancements to the `ColumnFilters` and `ColumnFilter` components by standardizing button sizes and improving reusability through shared constants. It also updates the theme to support the new button size styling. Below are the most significant changes grouped by theme:
* Updated the `ColumnFilters` component to use a custom `renderButton` function for rendering the drawer's open button, ensuring consistent button size (`BUTTON_PROPS.SIZE.LARGE`). [[1]](diffhunk://#diff-7943c2b249358bc0e5edadf255b893d21cfd0f83798359ec50fc17b2b83625faL25-R27) [[2]](diffhunk://#diff-7943c2b249358bc0e5edadf255b893d21cfd0f83798359ec50fc17b2b83625faR39-R47)
* Added support for the `size` property in the `ColumnFilter` component's button, aligning it with the shared …
> feat: update data dictionary column filter button size to large (#603)

- src/components/Index/components/EntityView/components/views/ChartView/components/Chart/barX/plot.ts
- src/components/Index/components/EntityView/components/views/ChartView/components/Chart/chart.styles.ts
- src/components/Index/components/EntityView/components/views/ChartView/components/Chart/chart.tsx
- src/components/Index/components/EntityView/components/views/ChartView/components/Chart/hooks/UseBarCount/constants.ts
- src/components/Index/components/EntityView/components/views/ChartView/components/Chart/hooks/UseBarCount/hook.ts
- src/components/Index/components/EntityView/components/views/ChartView/components/Chart/hooks/UseBarCount/types.ts
- src/components/Index/components/EntityView/components/views/ChartView/components/Chart/hooks/UseBarCount/utils.ts
- src/components/Index/components/EntityView/components/views/ChartView/components/Chart/hooks/UsePlotOptions/hook.ts
- src/components/Index/components/EntityView/components/views/ChartView/components/Chart/hooks/UsePlotOptions/types.ts
- src/components/Index/components/EntityView/components/views/ChartView/components/Chart/utils.ts
- src/hooks/useCategoryFilter.ts
Closes #446.
This pull request introduces a new feature to make bar charts expandable, allowing users to toggle between a limited and full view of chart data. The implementation includes changes to the chart's rendering logic, supporting hooks, and utility functions. Additionally, the code has been refactored to improve modularity and maintainability.
* Added a `StyledButton` component to enable toggling between expanded and collapsed chart views. (`[src/components/Index/components/EntityView/components/views/ChartView/components/Chart/chart.styles.tsR32-R36](diffhunk://#diff-e1c498068c8e59d019aee839a3c1823f392e9c8cb81e009994159af81f074941R32-R36)`)
* Introduced the `useBarCount` hook to manage the state of the number of bars displayed, with utility functions for initialization and …
> feat: chart view - show more link for long tail charts (#446)

- src/styles/common/mixins/typography.ts
Closes #625.
This pull request adds a new utility function to support consistent typography styling using Emotion and theme variants.
New typography utility:
* Added the `typographyToCSS` function in `src/styles/common/mixins/typography.ts` to generate Emotion CSS styles for a given typography variant from the theme.
> feat: create typography to css helper function (#625)

- src/theme/common/typography.ts
Closes #630.
This pull request updates the typography styles in `src/theme/common/typography.ts` to improve visual consistency and readability across heading sizes. The main changes focus on adjusting letter spacing, font sizes, and line heights for headings at various breakpoints.
**Typography adjustments:**
* Increased negative letter spacing for all heading variants to create tighter text appearance, especially at larger breakpoints. (`heading`, `headingLarge`, `headingSmall`, `headingXLarge`) [[1]](diffhunk://#diff-005a20b3d16cacaaf2a1895326d6c1836fdfdbff2d3648128988bff93df92bc9R75-R79) [[2]](diffhunk://#diff-005a20b3d16cacaaf2a1895326d6c1836fdfdbff2d3648128988bff93df92bc9R88-R92) [[3]](diffhunk://#diff-005a20b3d16cacaaf2a1895326d6c1836fdfdbff2d3648128988bff93df92bc9R104) …
> fix:  revert typography theme styles (#630)

- src/components/Filter/components/adapters/tanstack/ColumnFiltersAdapter/types.ts
- src/components/Filter/components/adapters/tanstack/ColumnFiltersAdapter/utils.ts
Closes #632.
This pull request enhances the flexibility of the TanStack table filter adapter by introducing support for category groups and improving how category filters are constructed. The main changes focus on allowing multiple category groups, making the system more extensible and modular.
**Support for category groups and improved filter construction:**
* Added `ColumnFiltersTableMeta` type to extend TanStack's `TableMeta` with optional `categoryGroups`, enabling the use of grouped category filters.
* Updated `buildColumnFilters` to check for `categoryGroups` in table meta; if present, it builds filters from groups, otherwise it falls back to a single group with all filterable columns.
* Introduced helper functions: `buildCategoryConfigs`, `buildCategoryFilters`, …
> feat: update columnfiltersadapter to handle grouping of column filters (#632)

- src/common/categories/config/range/typeGuards.ts
- src/components/Filter/components/adapters/tanstack/ColumnFiltersAdapter/columnFiltersAdapter.tsx
- src/components/Filter/components/adapters/tanstack/ColumnFiltersAdapter/utils.ts
Closes #634.
This pull request refactors and extends the filtering adapter logic for TanStack tables, introducing support for range filters and category groups. The changes improve how category filters are constructed, making the codebase more modular and flexible for different filter types.
* Added support for range filters by introducing the `isRangeCategoryConfig` type guard and handling `VIEW_KIND.RANGE` in the filter application logic, enabling direct value assignment for numeric ranges. [[1]](diffhunk://#diff-9147d8f723fd54b8983ec74445fe169322e656dbe1bf65d7dc96b51223526c31R1-R14) [[2]](diffhunk://#diff-3642aec699fc505dfb2bc33b72272947aade8749abad7026d2c0e67de613abf6R3) [[3]](diffhunk://#diff-3642aec699fc505dfb2bc33b72272947aade8749abad7026d2c0e67de613abf6L25-R42)
* Refactored the …
> feat: update columnfiltersadapter to handle range category filtering (#634)

- src/components/Table/components/TableToolbar2/tableToolbar2.styles.ts
- src/components/Table/components/TableToolbar2/tableToolbar2.tsx
- src/components/Table/components/TableToolbar2/types.ts
> feat: create new tabletoolbar with download button - independent of explorestate (#653)

- src/components/Table/common/columnDef.ts
- src/components/Table/components/TableFeatures/TableDownload/tableDownload.tsx
- src/components/Table/featureOptions/tableDownload/constants.ts
- src/components/Table/features/TableDownload/constants.ts
- src/components/Table/features/TableDownload/onDownload/utils.ts
- src/components/Table/features/TableDownload/types.ts
- src/components/Table/features/TableDownload/utils.ts
- types/data-explorer-ui.d.ts
Closes #659.
This pull request refactors the table download feature to consistently use the `enableTableDownload` naming convention instead of the previous `enableDownload`, and updates related method and property names for clarity and consistency. The changes affect type definitions, feature options, utility functions, and component logic.
**Refactor to use `enableTableDownload` and related API updates:**
* Renamed all occurrences of `enableDownload` to `enableTableDownload` in type definitions, constants, and column definitions, including in `TableDownloadOptions`, `TableDownloadColumnDef`, and default options. [[1]](diffhunk://#diff-023deee38c25e8733b5da2fb5a7f73d711803b232d75cac6e1f9e05a22a5c431L4-R18) [[2]](diffhunk://#diff-649889f26cec8360ae1e9a323c41f2c889a18d1b4afb9259a49afa7ae4f7f …
> refactor: align table download feature more closely with tanstack standards (#659)

- src/components/Detail/components/Table/common/utils.ts
- src/components/Detail/components/Table/components/TableRows/components/CollapsableRows/collapsableRows.tsx
- src/components/Detail/components/Table/components/TableRows/tableRows.tsx
- src/components/Table/components/TableRow/tableRow.styles.ts
- src/components/Table/components/TableRows/components/CollapsableRows/collapsableRows.tsx
- src/components/Table/components/TableRows/tableRows.tsx
- src/components/TableCreator/options/hook.ts
Closes #665.
This pull request enhances the table row components to better support row selection and selection-based styling. The main changes include updating table row props and styles to reflect selection state, and ensuring that selection capability is visually indicated and correctly passed through the component hierarchy.
**Row selection support and styling:**
* Added `isSelected` and `canSelect` props to `StyledTableRow` and updated its styles to visually indicate when a row is selected or cannot be selected, using the appropriate colors from the `PALETTE` constants. (`src/components/Table/components/TableRow/tableRow.styles.ts`) [[1]](diffhunk://#diff-857569b13da2fc3d48bc294caab6c301affada6d453a6418a0c58d163c033209R9-R23) …
> feat: update table row to display disabled state (#665)
